FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 2. create a non-root user to run the agent 
RUN adduser --disabled-password agent_user

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

USER agent_user

# 6. copy all code to the container with the correct ownership
COPY --chown=agent_user:agent_user . .

# 7. Run the agent
CMD ["python", "-u", "agent.py"]